version: '3.8'
services:
  webmin:
    image: trucv/webmin:latest
    init: true
    volumes:
      - wconfig:/etc/webmin
    restart: always
    ports:
      - 10000:10000
    container_name: webmin
