version: '3.8'
services:
  webmin:
    build: .
    init: true
    volumes:
      - config:/etc/webmin
    restart: unless-stopped
    ports:
      - 10000:10000
    container_name: webmin
volumes:
  config: